package com.tahaalangar.countriesapp

object Constant {
    val dataList= listOf(
        CountryModel(R.drawable.india,"india","India is a diverse nation located in South Asia, known for its rich history, cultural heritage, and economic growth. With a population of over 1.3 billion people, India boasts a vibrant tapestry of languages, religions, and traditions, contributing to its status as the world's largest democracy. From the majestic Himalayas in the north to the tropical beaches of the south, India's geographical and cultural landscape captivates visitors and residents alike"),
        CountryModel(R.drawable.indonesia,"indonesia", "Indonesia is an archipelago nation located in Southeast Asia, comprising over 17,000 islands, including Java, Sumatra, Borneo, and Bali. With a population exceeding 270 million people, it is the fourth most populous country in the world. Indonesia is renowned for its diverse cultures, languages, and landscapes, ranging from lush rainforests and volcanoes to vibrant cities and pristine beaches. As a major player in the global economy, Indonesia possesses rich natural resources and a growing tourism industry, making it a fascinating destination for travelers and investors alike."),
        CountryModel(R.drawable.unitedkingdom,"unitedkingdom","The United Kingdom (UK) is a sovereign country located off the northwestern coast of mainland Europe. Comprising four constituent nations: England, Scotland, Wales, and Northern Ireland, it boasts a rich history, diverse culture, and global influence. Renowned for landmarks such as Big Ben, Buckingham Palace, and Stonehenge, the UK is also known for its contributions to literature, music, and science. With a parliamentary democracy and a constitutional monarchy headed by Queen Elizabeth II, the UK plays a significant role in international affairs, business, and diplomacy."),
        CountryModel(R.drawable.unitedstates,"unitedstates","The United States of America (USA) is a vast and diverse nation located in North America, bordered by Canada to the north and Mexico to the south. Comprising 50 states, along with Washington, D.C., the capital district, the USA is known for its economic power, cultural influence, and political prominence. From the iconic skyline of New York City to the natural wonders of Yellowstone National Park and the Grand Canyon, the country offers a breathtaking array of landscapes and attractions. With a population exceeding 330 million people, the USA is a melting pot of cultures, languages, and traditions, shaped by waves of immigration throughout its history. As a global superpower, it plays a pivotal role in shaping international relations, trade, and innovation."),
        CountryModel(R.drawable.unitedstates,"unitedstates","The United States of America (USA) is a vast and diverse nation located in North America, bordered by Canada to the north and Mexico to the south. Comprising 50 states, along with Washington, D.C., the capital district, the USA is known for its economic power, cultural influence, and political prominence. From the iconic skyline of New York City to the natural wonders of Yellowstone National Park and the Grand Canyon, the country offers a breathtaking array of landscapes and attractions. With a population exceeding 330 million people, the USA is a melting pot of cultures, languages, and traditions, shaped by waves of immigration throughout its history. As a global superpower, it plays a pivotal role in shaping international relations, trade, and innovation."),
        CountryModel(R.drawable.easttimor,"easttimor","East Timor, officially known as the Democratic Republic of Timor-Leste, is a small sovereign nation located in Southeast Asia, occupying the eastern half of the island of Timor. It gained independence from Indonesia in 2002, making it one of the youngest countries in the world. Despite its size, East Timor possesses a rich cultural heritage, influenced by Portuguese colonization and indigenous traditions. Dili, the capital city, serves as the political and economic center, while the nation's rugged landscapes offer opportunities for ecotourism and adventure. Despite facing challenges such as poverty and infrastructure development, East Timor is striving to build a stable and prosperous future for its citizens."),
        CountryModel(R.drawable.france,"france", "France, officially known as the French Republic, is a country located in Western Europe, renowned for its rich history, culture, and contributions to art, philosophy, and cuisine. With Paris as its capital and largest city, France is famed for iconic landmarks such as the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral, drawing millions of tourists annually."),
        CountryModel(R.drawable.sweden,"sweden","Sweden, officially known as the Kingdom of Sweden, is a Nordic country located in Northern Europe. Renowned for its high standard of living, progressive social policies, and stunning natural beauty, Sweden is a constitutional monarchy with a parliamentary democracy."),
        CountryModel(R.drawable.singapore,"singapore","india is a country"),
        CountryModel(R.drawable.czechrepublic,"czechrepublic","india is a country"),
        CountryModel(R.drawable.denmark,"denmark","india is a country"),
        CountryModel(R.drawable.germanyy,"germanyy","india is a country"),
        CountryModel(R.drawable.thailand,"thailand","india is a country"),
        CountryModel(R.drawable.italy,"italy","india is a country"),
        CountryModel(R.drawable.australiaa,"australiaa","india is a country"),
        CountryModel(R.drawable.lithuania,"lithuania","india is a country"),
        CountryModel(R.drawable.netherlands,"netherlands","india is a country"),
        CountryModel(R.drawable.southkorea,"southkorea","india is a country"),
        CountryModel(R.drawable.vietnam,"vietnam","india is a country"),
        CountryModel(R.drawable.malaysia,"malaysia","india is a country"),
        CountryModel(R.drawable.poland,"poland","india is a country"),
        CountryModel(R.drawable.japan,"japan","india is a country"),
        CountryModel(R.drawable.spain,"spain","india is a country"),
        CountryModel(R.drawable.brazil,"brazil","india is a country"),
        CountryModel(R.drawable.canada,"canada","india is a country"),
        CountryModel(R.drawable.china,"china","india is a country"),
        CountryModel(R.drawable.europeanunion,"europeanunion","The European Union (EU) is a political and economic union of 27 member states primarily located in Europe. Initially established in the aftermath of World War II to foster economic cooperation and prevent further conflict, the EU has evolved into a complex organization with broad powers and responsibilities. Key objectives include promoting peace, stability, and prosperity among its members, as well as advancing common policies in areas such as trade, immigration, and environmental protection."),
        CountryModel(R.drawable.russia,"russia","Russia, officially known as the Russian Federation, is the largest country in the world by land area, spanning Eastern Europe and Northern Asia. With a rich history, diverse culture, and significant global influence, Russia plays a prominent role in geopolitics, economics, and culture."),

    )
}